name: test
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Wrapper
        run: "gradle wrapper"

      - name: Validate Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run Tests
        run: "./gradlew test --tests=org.*"

      - name: Submit Code Coverage
        run: |
          ./gradlew jacocoTestReport
          bash <(curl -s https://codecov.io/bash)
